### ISSUE TITLE
products can’t be saved via rest interface

### ISSUE THREAD

**Issue by sweiland** [colingit93/AP0Backend#29]
getting IntegrityError at /api/products/
NOT NULL constraint failed: virtbauernhof_product.farm_id

for product payloads with
"farm":{"id”:1,"images":[],"name”:"Farm","description”:"Test","farmer":1,"address":1}
,
"farm”:1
, and
”farm_id”:1

**Comment by GZEI** [comment]
should be fixed in master

**Comment by GZEI** [comment]
Please test fix. If problem persists, please reopen this issue.
