### ISSUE TITLE
AP1: Updates für den nächsten Sprint

### ISSUE THREAD

**Issue by Urb4nOutl4w** [colingit93/AP0Backend#47]
Bei der Abfrage nach dem Produkt bitte den Farmnamen mitgeben (Am besten gleich das gesamte Farmobjekt)
Bei den Produkten fehlt noch ein Preis, Bio, Public, Saisonal und Delivery Attribut. (Miro Board)
Wir können mittlerweile zwar Bilder hochladen, aber wenn man sie wieder anzeigen will kommt ein 404 Error, entweder fixen oder falls wir zu dumm sind bitte uns sagen wie man sie richtig anzeigt
Wenn wir Produkte und Farms laden bitte auch für jede Farm/Product eine liste ihrer Image Links mitgeben.
Wir benötigen Product- und Service-Categories Tables und bei den Products und Services entsprechende Attribute.

**Comment by GZEI** [comment]
Bitte die Aufgaben in einzelne Issues splitten damit diese sinnvoll zugeteilt und abgearbeitet werden können.
Der Mediaupload sollte im development branch gefixt sein.
